### ISSUE TITLE
Some playbooks do not use the configurable settings

### ISSUE THREAD

**Issue by kheops2713** [equalitie/eqpress#1]
play-init-provision.yml asks for "auto_provision_base_directory" setting, but it is not use in the main.yml task for the auto-provision role, which uses hardcoded /var/www/easypress.ca/provision. Is this normal?

**Comment by ghost** [comment]
This is not normal. This is work to be done. There is still some work to be done on this part of the repository before it's ready for testing.

**Comment by ghost** [comment]
0dd13de05ebb08b2e71e70788314f30d600657e4
