### ISSUE TITLE
All references to PHPMyAdmin must be removed

### ISSUE THREAD

**Issue by kheops2713** [equalitie/eqpress#12]

**Comment by ghost** [comment]
Done. 0304e4447c6d083cb530aebe78aadb8a0cd60898

**Comment by acataluddi** [comment]
@graphiclunarkid, I think this issue could be closed, isn't it?

**Comment by graphiclunarkid** [comment]
I agree. This issue doesn't specify _why_ we need to remove references to PHPMyAdmin; it is five months old; and @boreal says it's "done" in a contemporaneous commit.

If there's something we've missed we can always raise a new issue.
